[config]
default_to_workspace = false

[tasks.dev-api]
command = "cargo"
args = ["watch", "-x", "run", "-p", "api"]

[tasks.dev-web]
command = "pnpm"
args = ["--filter", "./apps/web", "run", "dev"]

[tasks.dev]
run_task = { name = ["dev-web", "dev-api"], parallel = true }

[tasks.build-wasm]
script = "wasm-pack build libs/game-logic --target web && cp libs/game-logic/pkg/*.{wasm,js,ts} apps/web/src/wasm/game-logic"

[tasks.dev-wasm]
command = "cargo"
args = ["watch", "-w", "libs", "-x", "make build-wasm"]
